#!/bin/bash -e

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source "${THIS_SCRIPT_DIR}/scripts/common"

source "${SCRIPTS_DIR}/conffiles"
source "${SCRIPTS_DIR}/cli"
source "${SCRIPTS_DIR}/commands"
source "${SCRIPTS_DIR}/fs"
source "${SCRIPTS_DIR}/services"

createFlagFile() {
    message $'\nCreating anthonyzation flag.'
    superUserDo bash -c "source \"${SCRIPTS_DIR}/anthonyize-create-flag-file\""
}

checkWeAreRunningBash() {
    if [ -z "$BASH_VERSION" ]; then
        messageError $'ERROR: anthonyize must be run using bash, not sh or another shell.\n'
        exit 1
    fi
}

anthonyize() {
    if [ "$(whoami)" == root ]; then
        messageError $'WARNING: Anthonyzation is running as root (did you use sudo?).'
        messageError $'The configurations will work but some will only apply to the'
        messageError $'root user, not to the unprivileged user. Note that you may'
        messageError $'want to do this so that a root shell will have your usual'
        messageError $'configuration too (when running the Anthonyzation as normal'
        messageError $'user, some of the configuration only applies to that user).\n'
    fi

    checkWeAreRunningBash || return

    message 'Checking for flag file.'
    if haveFlagFile; then
        messageStatus $'Already present; updating anthonyzation.\n'
    else
        messageStatus $'Not present; setting up anthonyzation.\n'
    fi
    tweakFilesystem || return
    installConfigFiles || return
    setupCli || return
    configureCommands || return
    setupServices || return
    createFlagFile || return
}

anthonyize || messageError $'An error occurred. Stop anthonyzation.\n'
