#!/usr/bin/env bash

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source "${THIS_SCRIPT_DIR}/scripts/common"

source "${SCRIPTS_DIR}/config"

anthonyize() {
    installConfigFiles
}

anthonyize
