#!/usr/bin/env bash

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source "${THIS_SCRIPT_DIR}/scripts/common"

source "${SCRIPTS_DIR}/conffiles"
source "${SCRIPTS_DIR}/cli"
source "${SCRIPTS_DIR}/commands"
source "${SCRIPTS_DIR}/fs"

createFlagFile() {
    message $'\nCreating anthonyzation flag...\n'
    sudo bash -c "source \"${SCRIPTS_DIR}/anthonyize-create-flag-file\""
}

anthonyize() {
    createFlagFile
    tweakFilesystem
    installConfigFiles
    setupCli
    configureCommands
}

anthonyize
