#!/bin/bash

# ==============================================================================
# =                      CREATED BY ANTHONYZATION SCRIPT                       =
# =                 https://github.com/adentinger/Anthonyize                  =
# ==============================================================================

source /etc/anthonyzation.d/bash_alias_completion

# EXPECTED PARAMS :
# 1 : the alias to autocomplete
completeAlias() {
    ALIAS="${1}"
    _add_completion_for_alias "${ALIAS}"
}

for alias in $(grep -oE 'alias[[:space:]]+[a-zA-Z0-9_]+[[:space:]]*=' /etc/anthonyzation.d/bash.bash_aliases | sed -E 's/^alias[[:space:]]+//' | sed -E 's/=[[:space:]]*//'); do
    completeAlias "${alias}"
done
