#!/bin/bash

# ==============================================================================
# =                      CREATED BY ANTHONYZATION SCRIPT                       =
# =                 https://github.com/AnthonyD973/Anthonyize                  =
# ==============================================================================

source /etc/anthonyzation.d/bash_alias_completion

# EXPECTED PARAMS :
# 1 : the alias to autocomplete
completeAlias() {
    ALIAS="${1}"
    _add_completion_for_alias "${ALIAS}"
}

for alias in $(grep -oE 'alias[[:space:]]+[a-zA-Z0-9_]+' /etc/anthonyzation.d/bash.bash_aliases); do
    completeAlias "${alias}"
done
