#!/bin/bash

source /etc/anthonyzation.d/bash.bash_aliases  # Setup aliases
source /etc/bash_completion.d/alias_completion # Setup alias completion

# Set tab stops to each column multiple of 4.
tabs 4

if command -v emacs >/dev/null; then
    export EDITOR=emacs
elif command -v nano >/dev/null; then
    export EDITOR=nano
fi

# Makes the prompt look like an Ubuntu prompt
export PS1=$'\[\033[01;32m\]\u\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
