#!/bin/bash -e

# Sets up bash to my habits

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source "${THIS_SCRIPT_DIR}/common"

# Append changes the bash.bashrc file whitout being too intrusive.
setupBashrc() {
    message $'\nSetting up bashrc'
    superUserDo bash -c "source \"${SCRIPTS_DIR}/cli-setup-bashrc\""
}

setDefaultShellToBash() {
    if [ "$SHELL" != "/bin/bash" ]; then
        messageStatus 'Setting default shell to bash.'
        chsh -s /bin/bash
    fi
}

# Sets up bash
setupCli() {
    setDefaultShellToBash || return
    if ! haveFlagFile; then
        message 'Setting up bash.'
        setupBashrc || return
    else
        messageStatus 'Anthonyzation already run; not setting up bash.'
        return 0
    fi
}
