#!/usr/bin/env bash
# Sets up bash to my habits

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source "${THIS_SCRIPT_DIR}/common"

# Append changes the bash.bashrc file whitout being too intrusive.
setupBashrc() {
    message $'\nSetting up bashrc\n'
    sudo bash -c "source \"${SCRIPTS_DIR}/cli-setup-bashrc\""
}

# Sets up bash
setupCli() {
    setupBashrc
}
