#!/bin/bash -e

# Script which is meant to be executed as sudo.

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source "${THIS_SCRIPT_DIR}/common"

setupBashrc() {
    local BASHRC_PLACES=("/etc/bashrc" "/etc/bash.bashrc" "/etc/bash.bashrc.local")
    for bashrc in "${BASHRC_PLACES[@]}"; do
        if [ -f "${bashrc}" ]; then
            local BASHRC_FILE="${bashrc}"
            break
        fi
    done

    if [ "${BASHRC_FILE}" == "" ]; then
        messageError $'\nCannot find bashrc file.\n'
        exit 1
    fi

    echo >> "${BASHRC_FILE}" # In case there was no empty line beforehand
    echo '# ==============================================================================' >> "${BASHRC_FILE}"
    echo '# =                        ADDED BY ANTHONYZATION SCRIPT                       =' >> "${BASHRC_FILE}"
    echo '# =                 https://github.com/AnthonyD973/Anthonyize                  =' >> "${BASHRC_FILE}"
    echo '# ==============================================================================' >> "${BASHRC_FILE}"
    echo 'source /etc/anthonyzation.d/bash.bash_aliases  # Setup aliases' >> "${BASHRC_FILE}"
    echo 'source /etc/bash_completion.d/alias_completion # Setup alias completion'>> "${BASHRC_FILE}"
    echo >> "${BASHRC_FILE}"
    echo '# Makes the prompt look like an Ubuntu prompt' >> "${BASHRC_FILE}"
    echo $'export PS1=\'\[\033[01;32m\]\u\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ \'' >> "${BASHRC_FILE}"
}

setupBashrc
