#!/usr/bin/env bash

# Script sourced by all other scripts. Used e.g. to
# set variables common to all scripts.

# =============================================================================
# =                            VARIABLE DEFINITIONS                           #
# =============================================================================

# Directory containing this script
THIS_SCRIPT_DIR="$(cd "$(dirname ${BASH_SOURCE[0]})" > /dev/null && pwd)"
# Root of the Git repo
GIT_ROOT="${THIS_SCRIPT_DIR}/.."
# Directory containing the scripts
SCRIPTS_DIR="${GIT_ROOT}/scripts"
# Directory containing the config files
CONFIG_DIR="${GIT_ROOT}/config"
# File indicating that the anthonyzation script was run (but does not guarantee
# it was completed).
ANTHONYZATION_FLAG="/etc/anthonyzation.d/anthonyzation-was-run"

# =============================================================================
# =                              FUNCTION DEFINITIONS                         #
# =============================================================================


# EXPECTED PARAMS:
# any amount
message() {
    echo -n -e '\e[1;92m'
    echo "$@"
    echo -n -e  '\e[0m'
}

# EXPECTED PARAMS:
# any amount
messageError() {
    echo -n -e '\e[1;91m'
    echo "$@" >&2
    echo -n -e '\e[0m'
    false
}

