#!/usr/bin/env bash
# Copy the config files to the system.

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source "${THIS_SCRIPT_DIR}/common"

installConfigFiles() {
    message $'\nInstalling configuration files. Need root credentials.\n'
    sudo rsync -ru "${CONFIG_DIR}" /
}

