#!/usr/bin/env bash
# Create filesystem directories

tweakFilesystem() {
    mkdir -p ~/Git
    mkdir -p ~/Desktop # No matter whether we have a GUI ;
                       # Desktop is a sort of catch-all directory for whatever
                       # is only here temporarily
}
