#!/usr/bin/env bash
# Create filesystem directories

tweakFilesystem() {
    mkdir -p ~/Git
    mkdir -p ~/Desktop # No matter whether we have a GUI ; I consider
                       # Desktop to be a sort of catch-all directory for whatever
                       # I use temporarily
}
