#!/bin/bash

################################
# CREATED BY ANTHONY DENTINGER #
################################

source /etc/bash_completion.d/bash_alias_completion

# EXPECTED PARAMS :
# 1 : the alias to autocomplete
completeAlias() {
    ALIAS="${1}"
    complete -F _complete_alias "${ALIAS}"
}

for alias in $(grep -Po '^alias\s+\w+(?==)' /etc/bash.bash_aliases | grep -Po '(?<=\s)\w+'); do
    completeAlias "${alias}"
done
